// Single source for the Country dropdown in all contact form variants
// (ContactForm, ContactFormSuperSlimOnly, ContactFormSuperSlimOnlyNoNL).
//
// The list is deliberately short: markets we actually sell into (EU/EEA,
// North America, the Latin America partner region, UK, major APAC tech
// markets, Israel/Gulf, South Africa, Turkey, Ukraine). Countries under
// EU/US sanctions are excluded on purpose — do not re-add them. Everyone
// else picks "Other".
//
// The server-side email routing (functions/lib/sendgrid.js,
// countryNameToCode) matches on these exact English names; "Other" and any
// unmapped name fall through to the default template.

export const CONTACT_FORM_COUNTRIES = [
  'United States',
  'Argentina',
  'Australia',
  'Austria',
  'Belgium',
  'Bolivia',
  'Brazil',
  'Bulgaria',
  'Canada',
  'Chile',
  'Colombia',
  'Costa Rica',
  'Croatia',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Dominican Republic',
  'Ecuador',
  'Estonia',
  'Finland',
  'France',
  'Germany',
  'Greece',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Ireland',
  'Israel',
  'Italy',
  'Japan',
  'Latvia',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Malta',
  'Mexico',
  'Netherlands',
  'New Zealand',
  'Norway',
  'Panama',
  'Paraguay',
  'Peru',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Romania',
  'Saudi Arabia',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'South Africa',
  'South Korea',
  'Spain',
  'Sweden',
  'Switzerland',
  'Taiwan',
  'Turkey',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'Uruguay',
  'Other',
];
